name: build subjects

on:
  schedule:
    # 09:31 every Wednesday
    - cron: '31 9 * * 3'
  workflow_dispatch:

jobs:
  build_date:
    runs-on: ubuntu-latest
    name: Generate BUILD_DATE
    steps:
    - name: Get current date
      id: date
      run: echo "BUILD_DATE=$(date +'+%A %W %Y %X')" >> $GITHUB_OUTPUT
    outputs:
      BUILD_DATE: ${{ steps.date.outputs.BUILD_DATE }}
  build_image:
    name: Build image and publish subjects
    runs-on: ubuntu-latest
    needs: build_date
    steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Zooniverse-SLSN
      uses: docker/build-push-action@v4
      with:
        push: false
        tags: |
          ghcr.io/zooniverse/zooniverse-slsn:test
          ghcr.io/zooniverse/zooniverse-slsn:${{ github.sha }}
        build-args: |
          BUILD_DATE=${{ needs.build_date.outputs.BUILD_DATE }}
          PANOPTES_USERNAME=${{ secrets.PANOPTES_USERNAME }}
          PANOPTES_PASSWORD=${{ secrets.PANOPTES_PASSWORD }}
          LASAIR_TOKEN=${{ secrets.LASAIR_TOKEN }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
